# Simple set of rules for GitHub actions integration with a ROS project
#

name: Build

on:
  push:
    branches: [main, jazzy]
  pull_request:

env:
  CORTEX_PATH: ${{ github.workspace }}/cortex

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.7.9
      - name: Install dependencies
        uses: ros-tooling/action-ros-ci@0.3.15
        with:
          package-name:
            rasa_bt
            rasa_msgs
            rasa_ros
          target-ros2-distro: jazzy
          colcon-defaults: |
            {
              "build": {
                "mixin": ["coverage-gcc", "coverage-pytest"]
              },
              "test": {
                "mixin": ["coverage-pytest"]
              }
            }
          skip-tests: false
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.4.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ros_ws/lcov/total_coverage.info,ros_ws/coveragepy/.coverage
          flags: unittests
          name: codecov-umbrella
          slug: grupo-avispa/rasa_ros
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests